### ISSUE TITLE
Could you give more instructions on the preparation of the dataset?

### ISSUE THREAD

**Issue by Namzakku** [captanlevi/Meaning-guided-video-captioning-#1]
Hi! Thanks for the great work!
I'm trying to follow your instructions and encounter some files that I did not quite know how to prepare. 
Can you give more details on these files? 
`wordtoindex.pickle,
indextoword.pickle,
embedding.npy
`
Thank you and looking forward to your response!

**Comment by captanlevi** [comment]
Hello , 
So wordtoindex and indextoword is essentially your vocabulary , and is created by making a pass over all your captions , extract all the unique words and assign each word an unique index , this structure is stored in a python dictionary , and saved as a pickle file , the index to word is just the opposite mapping .....

In my case I have also included some other common words from Google word2vec , to have a larger sized vocabulary.

Now for embedding,this is a (vocab, embedding_dim) size vector , so each word is assigned an embedding, (a 300 dimensional vector) , to produce embeddings , loop over all the unique words in order of their index ( 0 to n) and if the word exist in Google word2vec then assign this word to the index ie embeddings[I] = vector ,
Else just assign a random vector of 300 dimension.
( You have to set the embeddings as trainable if there are a lot of random vectors )

Hope this helps , if you want in can share the drive link to the vocabulary and embeddings I have already made .
I have also prepared an end to end code , that takes just a video path as input and returns the caption , let me know if you need that too....
Cheers

**Comment by Namzakku** [comment]
ohh I see! 
I want to give it a try with my dataset so I really appreciate if you could share the drive link to your vocabulary and embeddings!
And it will be much more wonderful if you could share the end to end code too, captain Levi!!

**Comment by captanlevi** [comment]
Umm , you will have to provide you gmail ID so that I can share the entire folder .....

**Comment by captanlevi** [comment]
Here is the viewable [Link](https://drive.google.com/drive/folders/1Gi-tuhQKydaN9ZBAmPrSMc6OrDHJMZdv?usp=sharing)

**Comment by Namzakku** [comment]
oh sorry for the late reply! my gmail is namntt@gmail.com.
Thanks for the link!

**Comment by captanlevi** [comment]
Should I close the issue now then ?
